language: php

php:
  - 7.2
  - 7.3

env:
  global:
    - TARGET=test

matrix:
  fast_finish: true
  include:
    - php: 7.3
      env: TARGET=cs_dry_run

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install: composer install --prefer-dist --no-interaction

script:
  - make $TARGET

after_success:
  - bash <(curl -s https://codecov.io/bash)